name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.100.0'
          extended: true
      
      - name: Build
        run: hugo --minify --baseURL "${{ github.event_name == 'pull_request' && (format('https://{0}-dyinglightthebeast-wiki.pages.dev', github.event.number)) || 'https://dyinglightthebeast.online' }}"
      
      - name: Deploy to Cloudflare Pages
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: dyinglightthebeast-wiki
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Preview deployment ready! Check it out at: https://${{ github.event.number }}-dyinglightthebeast-wiki.pages.dev'
            })
